name: Fuzz Parser

on:
  push:
    branches: [master]
    paths:
      - grammars/sml/src/scanner.c
  pull_request:
    paths:
      - grammars/ocaml/src/scanner.c

jobs:
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [grammars/sml]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fuzz ${{matrix.language}} parser
        uses: tree-sitter/fuzz-action@v4
        with:
          directory: ${{matrix.language}}
