name: Fuzz Parser

on:
  push:
    branches: [main]
    paths:
      - src/scanner.c
      - src/parser.c
  pull_request:
    paths:
      - src/scanner.c
      - src/parser.c

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fuzz parser
        uses: tree-sitter/fuzz-action@v4
